### ISSUE TITLE
Full Scene-Cache not working

### ISSUE THREAD

**Issue by ataulien** [REGoth-project/REGoth-bs#10]
You should be able to load *everything* from cache, the full scene, that is. There is no need to ever open the .ZEN-file again after the caching mechanism went through it. Loading from cache is orders of magnitude faster than relaying on the .ZEN-file since I think it uses multithreading under the hood.

However, there is a problem with the physics mesh of the world: If we load the world-mesh from cache, the physics mesh seems broken and does not do any collision with other objects.

**Comment by mworchel** [comment]
Guess this was fixed with https://github.com/REGoth-project/REGoth-bs/commit/bea146d83fd9a0b491099ebe6328bec0439fb0dc

Just for documentation: The physics mesh you construct to be used by the MeshCollider is a resource that also has to be saved.
