### ISSUE TITLE
Can not Build ReGoth

### ISSUE THREAD

**Issue by TimeFreeze1337** [REGoth-project/REGoth-bs#116]
Tried to build it followed instructions on https://regoth-project.github.io/REGoth-bs/getting-started/building-regoth.html . After that when i tried this Step: 

#Run CMake.
$ cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ..

Everything fine so far until:

-- Looking for LibUUID...
CMake Error at lib/bsf/Source/CMake/Modules/FindLibUUID.cmake:22 (message):
  Cannot find LibUUID.
Call Stack (most recent call first):
  lib/bsf/Source/Foundation/CMakeLists.txt:24 (find_package)

-- Configuring incomplete, errors occurred!
[CMakeOutput.log](https://github.com/REGoth-project/REGoth-bs/files/4016729/CMakeOutput.log)

**Comment by KirmesBude** [comment]
What OS/Distribution are you on? 
You should be able to find 'uuid-dev' or something similar in your package manager.

**Comment by TimeFreeze1337** [comment]
Thanks now it worked. Maybe they should include it in the Wiki as an Dependency?

And for what Distro: KDE Neon (Ubuntu)
