### ISSUE TITLE
ReGoth crashing on start up.

### ISSUE THREAD

**Issue by TimeFreeze1337** [REGoth-project/REGoth-bs#117]
When trying ReGoth it starts but then it crashs. And when trying ReGothWorldViewer for example i get this error: 

[INFO] No game asset path given. Trying executable path...
[INFO] Succeded
Segmentation fault

And below the crash Report for ReGoth itself.
[log.zip](https://github.com/REGoth-project/REGoth-bs/files/4022206/log.zip)

**Comment by KirmesBude** [comment]
Sorry for the late reply. 
The cli is not very obvious and also leads to a crash for me before printing any useful information. 

Slightly inaccurate information ahead (currently not at home to check): 
./REGoth -g PathToGothic 
e.g. ./REGoth -g /home/bude/Games/Gothic/

For the WorldViewer you have to provide another argument with -w (world). 
Pretty sure you have to omit the .ZEN at the end. 
e.g. ./REGothWorldViewer -g /home/bude/Games/Gothic -w OLDMINE

**Comment by TimeFreeze1337** [comment]
Oh thats disappointing. Anyway thanks for the answer!
