### ISSUE TITLE
Exploding triangles

### ISSUE THREAD

**Issue by ataulien** [REGoth-project/REGoth-bs#13]
Sometimes one can see messed up triangles, going all over the place. You cannot move away from them, they just stay attached to the camera. 

I have no idea what that is caused by, but I can see it happen in the `REGothWorldViewer` where many characters are added to the world. Probably one of the NPCs is broken, we should find out which one it is.

**Comment by mworchel** [comment]
I *think* I know what you mean. I experienced something like this when working on the shader. Sometimes it was caused by an old cache and sometimes it was caused by semantic (?) errors in the shader. I encountered this multiple times when trying to multiply a `float3` with a `float`. I totally don't know why that happens and what exactly causes it doesn't seem like an issue related to our meshes.

**Comment by ataulien** [comment]
Often I can just reload the world from cache and the triangles disappear and everything is fine...

**Comment by mworchel** [comment]
Ever experienced it since we used the new world shader?

**Comment by ataulien** [comment]
Yes, I get it once in a while, but it seems to be only happening when Skeletal-Meshes are in the world...

**Comment by mworchel** [comment]
Hm, strange. Maybe I don't mean the same thing. Will try to make a screen capture the next time I encounter it.

**Comment by ataulien** [comment]
![image](https://user-images.githubusercontent.com/11406580/57805749-d9211a80-775d-11e9-9ff7-fca4f2ecf7e6.png)

This is on the Waynet-Tester, so no skeletal meshes...

**Comment by mworchel** [comment]
Just adding my screenshot of a world with skeletal meshes and what appears to be also some kind of exploding triangles (for documentation). However I'm not sure it is the same issue as in your image.

![broken](https://user-images.githubusercontent.com/9449513/57876918-d33b4000-7816-11e9-8b6a-1d3e70905fff.PNG)

**Comment by mworchel** [comment]
This is the visual bug, I was talking about earlier. It seems to be shader-related though. (However is reading this, don't be confused by the weird colors. They have nothing to do with the bug :D )

![triangle_bug](https://user-images.githubusercontent.com/9449513/57971505-6dbe8f00-798f-11e9-964f-662d5f84ee4c.gif)

**Comment by ataulien** [comment]
I ran this through a graphics debugger and it seems like the issue is in fact caused by skeletal meshes. Look at some of the values for the shader uniforms here:

![image](https://user-images.githubusercontent.com/11406580/58247021-f014cd80-7d58-11e9-85b2-7205478390cc.png)

I've seen draw-calls with the human body texture bound, but also the bloodfly-texture. Since it's the inverse world matrix that is broken I don't think this is an animation issue...

**Comment by mworchel** [comment]
The world matrix looks broken aswell. See the `2.09...e+27` in its second row.

**Comment by ataulien** [comment]
I've seen that, but luckily that part of the world matrix was intact for some objects. I found one of the positions of such an object to belong to some dude in the new camp. No idea which one, seems to be random.

If you take a look at the first row, the `9512030784454656` as X-position also looks suspicious. The whole matrix is broken...

But there's also good news! Since I updated bsf to the latest master I have yet to see a single one of those exploding triangles! The only remaining issue is that some geometry seems to flicker...

**Comment by mworchel** [comment]
Oh right, didn't see the broken `x` translation... thought it would be `9.51...`. Maybe it was bsf related but time will tell.

What do you mean with flickering geometry?

**Comment by ataulien** [comment]
Some textures disappear for one frame every once in a while. But it's not that bad.

**Comment by mworchel** [comment]
I've never seen that. Maybe try to make a clip of it if you encounter it again.

**Comment by ataulien** [comment]
I tried, but the lower framerate makes it looks a little bit better:

![peekYPG51Z](https://user-images.githubusercontent.com/11406580/58347947-7a475980-7e5f-11e9-9bbf-b448f02bf41d.gif)

**Comment by ataulien** [comment]
Got one more gif with more flickering:

![peekXT801Z](https://user-images.githubusercontent.com/11406580/58352867-2a6f8f00-7e6d-11e9-8adb-eb854703bfaf.gif)

**Comment by ataulien** [comment]
Fixed in latest bsf-master.
