### ISSUE TITLE
Commandline interface to REGoth

### ISSUE THREAD

**Issue by ataulien** [REGoth-project/REGoth-bs#23]
Right now, each sample just defines the world it is supposed to load. While this makes sense for some specialized samples, some are so generic, that the user should be able to choose the world to load from the commandline.

For example:

```
./REGothWorldViewer ~/games/Gothic2 -w ADDONWORLD
```

Other flags for loading `.mod`-packages would also be helpful.

**Comment by ataulien** [comment]
@charlydelta I assume we can close this?

**Comment by charlydelta** [comment]
Oh look at that, I wasn't even aware of that issue (or forgot it in the meantime). I think so, yes ;)

However I only implemented this exact use-case, I didn't know enough for the other executables to add useful command line arguments. But the APIs are there now

**Comment by ataulien** [comment]
Then we should make a new issue for that

**Comment by charlydelta** [comment]
Yes I think so, too. Also:

> Other flags for loading `.mod`-packages would also be helpful.

I didn't look into this either.
