### ISSUE TITLE
Make default constructors used for RTTI private

### ISSUE THREAD

**Issue by mworchel** [REGoth-project/REGoth-bs#26]
A lot of classes inheriting directly or indirectly from `IReflectable` have a default constructor that is only used for RTTI and should not be accessible as part of the public interface. Due to the limitations of the current implementation, this default constructor is forced to be public like

**A.hpp**
```cpp
class A
{
public:
    A(parameters...);
    ...

public:             // FIXME: RTTI protected/private
     A() = default; // For RTTI
}
```

The need to make it public originates from the macro `REGOTH_IMPLEMENT_RTTI_CLASS_FOR_REFLECTABLE` which is used in the accompanying RTTI class and models instantiation of a dummy instance like

```cpp
bs::SPtr<bs::IReflectable> newRTTIObject() override          
{                                                            
  return bs::bs_shared_ptr_new<A>();                 
}   
```

To solve this issue, we could implement a scheme like bs::f does, which adds a static `createEmpty` method to the class itself:

**A.hpp**
```cpp
class A
{
public:
    A(parameters...);
    ...

public:
    static bs::SPtr<A> createEmpty();

private:
     A() = default; // For RTTI
}
```

**A.cpp**
```cpp
bs::SPtr<A> A::createEmpty()
{
    return bs::bs_shared_ptr(new (bs::bs_alloc<A>()) A());
}
```
The instantiation in the RTTI class could then be implemented like
```cpp
bs::SPtr<bs::IReflectable> newRTTIObject() override          
{                                                            
  return A::createEmpty();                 
}   
```

**Comment by ataulien** [comment]
This has been done in the last few PRs.
