### ISSUE TITLE
Found a Rock without Collision

### ISSUE THREAD

**Issue by ataulien** [REGoth-project/REGoth-bs#30]
This could be either a bug in our code or Piranha Bytes forgot to set the collision flag.

Either way, it would be nice if someone could check whether there is collision in the original game. If so, we need to hunt down the bug.

This is the Rock in question:
![Rock without collision](https://user-images.githubusercontent.com/9449513/57788775-f8a54c80-7737-11e9-9a93-ba1a77ec10bf.png)

It's in ADDONWORLD.ZEN just left when you leave the temple where you start from.
Remember that in REGoth everything is mirrored, so you'd have to go **right** in the original game!

**Comment by Jurigag** [comment]
Checked in original game and it's missing collision too.

**Comment by ataulien** [comment]
Should be fine on our side then. Thanks for testing!

**Comment by mworchel** [comment]
Not quite. I found several plants which have collision in `ADDONWORLD.ZEN` in REGoth which certainly shouldn't have collision in the original game (at least I assume so).

**Comment by Jurigag** [comment]
Will try to check those as well. It's near the bridge?

**Comment by mworchel** [comment]
That would be super helpful. It's just in front of the bridge if you are coming from the temple

**Comment by ataulien** [comment]
I found those myself and I know what's going on: There is a material flag to disable collision which we are ignoring. I'll make a new issue for it.
