### ISSUE TITLE
Backing up in Sneak-Mode

### ISSUE THREAD

**Issue by ataulien** [REGoth-project/REGoth-bs#53]
Were you able to go backwards while sneaking in the original game?

Right now you will just perform a normal step backwards while sneaking in REGoth. This isn't correct either way. So to close this issue we need to:

 - [x] Check how sneaking behaves in the original.
 - [x] Implement that behavior in REGoth

The entrypoint to *Taking a step backwards* is here:
https://github.com/REGoth-project/REGoth-bs/blob/bf141a6e017008d12e9bf56b93cbfd5c75cd56bd/src/components/CharacterAI.cpp#L127-L132

As of now, `isStateSwitchAllowed()` will just return true for `T_JUMPB` regardless of the state the character is in, or anything starting with `T_` really, which is why stepping backwards is possible while sneaking.

**Comment by mworchel** [comment]
When you are sneaking and go backwards, the hero will sneak backwards instead of doing the standard jump. I tried it in both, G1 and G2.

**Comment by KirmesBude** [comment]
The same is true for walking, btw.  
There are seperate animations for each mode.

**Comment by ataulien** [comment]
Implemented in 72bd74c.
