### ISSUE TITLE
Jumping animation can get stuck

### ISSUE THREAD

**Issue by ataulien** [REGoth-project/REGoth-bs#55]
Go into walk mode, jump and then press forward mid jump and you get stuck in the jump animation until you let go of forward. There must be a problem with the transition between the weird `STAND` state, which does not really exist, and `WALK`.

Must be somewhere around in that file or the related ones: https://github.com/REGoth-project/REGoth-bs/blob/master/src/components/CharacterAI.cpp

This also works for walk/sneak when holding forward in the middle of the backup move.

**Comment by KirmesBude** [comment]
Maybe we should split up this issue or rename it? 
The second case
> This also works for walk/sneak when holding forward in the middle of the backup move. 

Does not really have anything to do with jumping.

**Comment by ataulien** [comment]
I hope that the root cause is the same for both: For some reason the animation transition is lost.
